name: Sync to Mirrors

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configurar git
        run: |
          git config user.name "sync-bot"
          git config user.email "sync@bot.com"

      - name: Sync mirror
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote remove mirror_update || true
          git remote add mirror_update https://x-access-token:${GH_TOKEN}@github.com/segredounlock/sync-start-magic.git
          git push --mirror mirror_update
