name: Sync to Mirrors

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync UPDATERECARGASBRASIL
        run: |
          git remote add mirror_update https://x-access-token:${{ secrets.SYNC_UPDATERECARGASBRASIL }}@github.com/segredounlock/UPDATERECARGASBRASIL.git
          git push mirror_update main --force
